package GUI;

import Controller.QuanLyNhanVienController;
import java.awt.Color;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Min-NvT
 */
public class NhanVienGUI extends javax.swing.JPanel {
       
    public NhanVienGUI() {
        initComponents();
       setBackground(new Color(255, 255, 255));
        JpnTieuDe.setBackground(new Color(255, 255, 255));
       
        JcbGioiTinh.setBackground(Color.BLACK);
       
      
BtnThem.setBackground(new Color(0000));
BtnSua.setBackground(new Color(0000));
BtnXoa.setBackground(new Color(0000));
BtnCapNhat.setBackground(new Color(0000));
BtnXuatExcel.setBackground(new Color(0000));
BtnNhapExcel.setBackground(new Color(0000));   
BtnTimKiem.setBackground(new Color(0000));
        QuanLyNhanVienController controller = new QuanLyNhanVienController( 
               Jtb,JpnTable,BtnThem,BtnSua,BtnXoa,BtnCapNhat,BtnXuatExcel,JtfTimKiem,BtnTimKiem,JtfMaNhanVien,JtfHoNhanVien,JtfTenNhanVien,JcbGioiTinh,JtfNgaySinh,JtfDiaChi, JlbThongBao,BtnNhapExcel
    ,JtfSdt);        

        controller.setDataToTable();
        controller.setEvent();
        //DefaultTableModel model = (DefaultTableModel) Jtb.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnTieuDe = new javax.swing.JPanel();
        JlbTieuDe = new javax.swing.JLabel();
        JpnTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtb = new javax.swing.JTable();
        JlbTenTable = new javax.swing.JLabel();
        JlbThongBao = new javax.swing.JLabel();
        BtnTimKiem = new javax.swing.JButton();
        JtfTimKiem = new javax.swing.JTextField();
        BtnThem = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        BtnCapNhat = new javax.swing.JButton();
        BtnXuatExcel = new javax.swing.JButton();
        BtnNhapExcel = new javax.swing.JButton();
        JlbMaNhanVien = new javax.swing.JLabel();
        JtfMaNhanVien = new javax.swing.JTextField();
        JlbHo = new javax.swing.JLabel();
        JtfHoNhanVien = new javax.swing.JTextField();
        JlbTen = new javax.swing.JLabel();
        JtfTenNhanVien = new javax.swing.JTextField();
        JlbGioiTinh = new javax.swing.JLabel();
        JcbGioiTinh = new javax.swing.JComboBox<>();
        JlbSdt = new javax.swing.JLabel();
        JtfSdt = new javax.swing.JTextField();
        JlbNgaySinh = new javax.swing.JLabel();
        JtfNgaySinh = new javax.swing.JTextField();
        JlbDiaChi = new javax.swing.JLabel();
        JtfDiaChi = new javax.swing.JTextField();

        JlbTieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JlbTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbTieuDe.setText("NHÂN VIÊN");
        JlbTieuDe.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout JpnTieuDeLayout = new javax.swing.GroupLayout(JpnTieuDe);
        JpnTieuDe.setLayout(JpnTieuDeLayout);
        JpnTieuDeLayout.setHorizontalGroup(
            JpnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlbTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE)
        );
        JpnTieuDeLayout.setVerticalGroup(
            JpnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JpnTieuDeLayout.createSequentialGroup()
                .addComponent(JlbTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên", "Họ", "Giới Tính", "Ngày sinh", "Địa chỉ", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(Jtb);

        javax.swing.GroupLayout JpnTableLayout = new javax.swing.GroupLayout(JpnTable);
        JpnTable.setLayout(JpnTableLayout);
        JpnTableLayout.setHorizontalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        JpnTableLayout.setVerticalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        JlbTenTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JlbTenTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbTenTable.setText("BẢNG THÔNG TIN NHÂN VIÊN");

        JlbThongBao.setBorder(new javax.swing.border.MatteBorder(null));

        BtnTimKiem.setForeground(new java.awt.Color(255, 0, 0));
        BtnTimKiem.setText("Tìm Kiếm");
        BtnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        BtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimKiemActionPerformed(evt);
            }
        });

        BtnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnThem.setForeground(new java.awt.Color(255, 0, 51));
        BtnThem.setText("Thêm");
        BtnThem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        BtnThem.setHideActionText(true);
        BtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnThem.setInheritsPopupMenu(true);
        BtnThem.setName(""); // NOI18N
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        BtnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSua.setForeground(new java.awt.Color(255, 0, 0));
        BtnSua.setText("Sửa");
        BtnSua.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        BtnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXoa.setForeground(new java.awt.Color(255, 0, 0));
        BtnXoa.setText("Xóa");
        BtnXoa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        BtnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCapNhat.setForeground(new java.awt.Color(255, 0, 0));
        BtnCapNhat.setText("Cập Nhật");
        BtnCapNhat.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        BtnXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXuatExcel.setForeground(new java.awt.Color(255, 0, 0));
        BtnXuatExcel.setText("Xuất Excel");
        BtnXuatExcel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        BtnNhapExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNhapExcel.setForeground(new java.awt.Color(255, 0, 0));
        BtnNhapExcel.setText("Nhập Excel");
        BtnNhapExcel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        JlbMaNhanVien.setText("Mã nhân viên");

        JlbHo.setText("Họ ");

        JlbTen.setText("Tên");

        JlbGioiTinh.setText("Giới tính");

        JcbGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JcbGioiTinh.setForeground(new java.awt.Color(255, 0, 0));
        JcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        JcbGioiTinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbGioiTinhItemStateChanged(evt);
            }
        });
        JcbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbGioiTinhActionPerformed(evt);
            }
        });

        JlbSdt.setText("SĐT");

        JtfSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfSdtActionPerformed(evt);
            }
        });

        JlbNgaySinh.setText("Ngày sinh");

        JlbDiaChi.setText("Địa chỉ");

        JtfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfDiaChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JlbTenTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JpnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JpnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtfTimKiem)
                                .addGap(79, 79, 79)
                                .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JlbThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JlbHo)
                                    .addComponent(JlbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JlbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtfMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(JtfHoNhanVien)
                                    .addComponent(JtfTenNhanVien)
                                    .addComponent(JcbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlbSdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JlbNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JlbDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtfSdt, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(JtfNgaySinh)
                                    .addComponent(JtfDiaChi))))))
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JpnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(JlbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JlbMaNhanVien))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JtfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JlbSdt)
                        .addComponent(JtfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbHo)
                    .addComponent(JtfHoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbNgaySinh)
                    .addComponent(JtfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbTen)
                    .addComponent(JtfTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbDiaChi)
                    .addComponent(JtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbGioiTinh)
                    .addComponent(JcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(JlbTenTable)
                .addGap(18, 18, 18)
                .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void JtfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfDiaChiActionPerformed

    private void JcbGioiTinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbGioiTinhItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbGioiTinhItemStateChanged

    private void JcbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbGioiTinhActionPerformed

    private void JtfSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfSdtActionPerformed

    private void BtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimKiemActionPerformed

    }//GEN-LAST:event_BtnTimKiemActionPerformed

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXoaActionPerformed

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSuaActionPerformed

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed

    }//GEN-LAST:event_BtnThemActionPerformed


   
  public static void main(String args[]) {
       
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              JFrame f =  new JFrame();
              
              f.setVisible(true);
              f.setSize(1300, 800);
               f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               NhanVienGUI fr=new NhanVienGUI();
               fr.setSize(1200, 1000);
               f.add(fr);
               
               
            }
        });
    }
  
  
  
 
/*public void listSP() // Chép ArrayList lên table
    {
        if(nvBUS.getList()== null)nvBUS.listNV();
        ArrayList<NhanVienDTO> nv = nvBUS.getList();
        model.setRowCount(0);
        outModel(model,nv);
}

         try{
       
                        //Lấy dữ liệu từ TextField
                        String maNV = JtfMaNhanVien.getText();
                        String tenNV = JtfTenNhanVien.getText();                
                        String chucVu =JtfChucVu.getText();
                        String gioiTinh =JtfGioiTinh.getText();
                        String diaChi = JtfDiaChi.getText();
                        String email = JtfEmail.getText();
                        int namSinh = Integer.parseInt(JtfNamSinh.getText());
                        int mucLuong = Integer.parseInt(JtfMucLuong.getText());
                        int sdt = Integer.parseInt(JtfSoDienThoai.getText());

                        if(nvBUS.check(maNV))
                        {
                            JOptionPane.showMessageDialog(null, "Mã nhân viên đă tồn tại !!!");
                            return;
                        }
                        //Upload nhân viên lên DAO và BUS
                        NhanVienDTO nv = new NhanVienDTO(maNV, tenNV, chucVu, gioiTinh, diaChi,  email, namSinh,  mucLuong, sdt);
                        nvBUS.Them(nv);
                        outModel(model, nvBUS.getList());// Load lại table

                     
                            
                        //cleanView();
                         }catch(NumberFormatException ex){
                            JOptionPane.showMessageDialog(null,"Loi");
                        }
                    */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCapNhat;
    private javax.swing.JButton BtnNhapExcel;
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnTimKiem;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JButton BtnXuatExcel;
    private javax.swing.JComboBox<String> JcbGioiTinh;
    private javax.swing.JLabel JlbDiaChi;
    private javax.swing.JLabel JlbGioiTinh;
    private javax.swing.JLabel JlbHo;
    private javax.swing.JLabel JlbMaNhanVien;
    private javax.swing.JLabel JlbNgaySinh;
    private javax.swing.JLabel JlbSdt;
    private javax.swing.JLabel JlbTen;
    private javax.swing.JLabel JlbTenTable;
    private javax.swing.JLabel JlbThongBao;
    private javax.swing.JLabel JlbTieuDe;
    private javax.swing.JPanel JpnTable;
    private javax.swing.JPanel JpnTieuDe;
    private javax.swing.JTable Jtb;
    private javax.swing.JTextField JtfDiaChi;
    private javax.swing.JTextField JtfHoNhanVien;
    private javax.swing.JTextField JtfMaNhanVien;
    private javax.swing.JTextField JtfNgaySinh;
    private javax.swing.JTextField JtfSdt;
    private javax.swing.JTextField JtfTenNhanVien;
    private javax.swing.JTextField JtfTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getBackground(Color MAGENTA) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}