package GUI;

import Controller.QuanLyNhanVienController;
import java.awt.Color;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Min-NvT
 */
public class NhanVienGUI extends javax.swing.JPanel {
       
    public NhanVienGUI() {
        initComponents();
       setBackground(new Color(255, 255, 255));
        JpnTieuDe.setBackground(new Color(255, 255, 255));
        JpnChucNang.setBackground(new Color(255, 255, 255));
        JpnThongTin.setBackground(new Color(255, 255, 255));
        JcbGioiTinh.setBackground(Color.BLACK);
        JcbChucVu.setBackground(Color.BLACK);
      
BtnThem.setBackground(new Color(0000));
BtnSua.setBackground(new Color(0000));
BtnXoa.setBackground(new Color(0000));
BtnCapNhat.setBackground(new Color(0000));
BtnXuatExcel.setBackground(new Color(0000));
BtnNhapExcel.setBackground(new Color(0000));   
BtnTimKiem.setBackground(new Color(0000));
        QuanLyNhanVienController controller = new QuanLyNhanVienController( 
               Jtb,JpnTable,BtnThem,BtnSua,BtnXoa,BtnCapNhat,BtnXuatExcel,JtfTimKiem,BtnTimKiem,JtfMaNhanVien,JtfHoNhanVien,JtfTenNhanVien,JcbGioiTinh,JtfNgaySinh,JtfDiaChi,JtfKinhNghiem,JtfPhongBan,JcbChucVu,JtfLuong, JlbThongBao,JlbTB,BtnNhapExcel
    ,JtfSdt,JtfEmail);
        

        controller.setDataToTable();
        controller.setEvent();
        //DefaultTableModel model = (DefaultTableModel) Jtb.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnChucNang = new javax.swing.JPanel();
        JtfTimKiem = new javax.swing.JTextField();
        BtnThem = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        BtnCapNhat = new javax.swing.JButton();
        BtnNhapExcel = new javax.swing.JButton();
        BtnXuatExcel = new javax.swing.JButton();
        BtnTimKiem = new javax.swing.JButton();
        JlbTenChucNang = new javax.swing.JLabel();
        JpnThongTin = new javax.swing.JPanel();
        JlbMaNhanVien = new javax.swing.JLabel();
        JlbTen = new javax.swing.JLabel();
        JlbChucVu = new javax.swing.JLabel();
        JlbDiaChi = new javax.swing.JLabel();
        JlbHo = new javax.swing.JLabel();
        JtfMaNhanVien = new javax.swing.JTextField();
        JtfTenNhanVien = new javax.swing.JTextField();
        JtfDiaChi = new javax.swing.JTextField();
        JtfHoNhanVien = new javax.swing.JTextField();
        JlbTenThongTin = new javax.swing.JLabel();
        JlbNgaySinh = new javax.swing.JLabel();
        JtfNgaySinh = new javax.swing.JTextField();
        JlbGioiTinh = new javax.swing.JLabel();
        JcbGioiTinh = new javax.swing.JComboBox<>();
        JcbChucVu = new javax.swing.JComboBox<>();
        JtfKinhNghiem = new javax.swing.JTextField();
        JlbKinhNghiem = new javax.swing.JLabel();
        JtfPhongBan = new javax.swing.JTextField();
        JlbPhongBan = new javax.swing.JLabel();
        JlbSdt = new javax.swing.JLabel();
        JlbEmail = new javax.swing.JLabel();
        JtfSdt = new javax.swing.JTextField();
        JtfEmail = new javax.swing.JTextField();
        JlbLuong = new javax.swing.JLabel();
        JtfLuong = new javax.swing.JTextField();
        JpnTieuDe = new javax.swing.JPanel();
        JlbTieuDe = new javax.swing.JLabel();
        JlbThongBao = new javax.swing.JLabel();
        JlbTB = new javax.swing.JLabel();
        JpnTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtb = new javax.swing.JTable();
        JlbTenTable = new javax.swing.JLabel();

        BtnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnThem.setForeground(new java.awt.Color(255, 0, 51));
        BtnThem.setText("Thêm");
        BtnThem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        BtnThem.setHideActionText(true);
        BtnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnThem.setInheritsPopupMenu(true);
        BtnThem.setName(""); // NOI18N
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        BtnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSua.setForeground(new java.awt.Color(255, 0, 0));
        BtnSua.setText("Sửa");
        BtnSua.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        BtnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXoa.setForeground(new java.awt.Color(255, 0, 0));
        BtnXoa.setText("Xóa");
        BtnXoa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        BtnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCapNhat.setForeground(new java.awt.Color(255, 0, 0));
        BtnCapNhat.setText("Cập Nhật");
        BtnCapNhat.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        BtnNhapExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNhapExcel.setForeground(new java.awt.Color(255, 0, 0));
        BtnNhapExcel.setText("Nhập Excel");
        BtnNhapExcel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        BtnXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnXuatExcel.setForeground(new java.awt.Color(255, 0, 0));
        BtnXuatExcel.setText("Xuất Excel");
        BtnXuatExcel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        BtnTimKiem.setForeground(new java.awt.Color(255, 0, 0));
        BtnTimKiem.setText("Tìm Kiếm");
        BtnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        BtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimKiemActionPerformed(evt);
            }
        });

        JlbTenChucNang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JlbTenChucNang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbTenChucNang.setText("CHỨC NĂNG");
        JlbTenChucNang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout JpnChucNangLayout = new javax.swing.GroupLayout(JpnChucNang);
        JpnChucNang.setLayout(JpnChucNangLayout);
        JpnChucNangLayout.setHorizontalGroup(
            JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnChucNangLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnChucNangLayout.createSequentialGroup()
                        .addComponent(BtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JtfTimKiem))
                    .addGroup(JpnChucNangLayout.createSequentialGroup()
                        .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnNhapExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 56, Short.MAX_VALUE)
                        .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnXuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addComponent(JlbTenChucNang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpnChucNangLayout.setVerticalGroup(
            JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlbTenChucNang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        JpnThongTin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        JlbMaNhanVien.setText("Mã nhân viên");

        JlbTen.setText("Tên");

        JlbChucVu.setText("Chức vụ");

        JlbDiaChi.setText("Địa chỉ");

        JlbHo.setText("Họ ");

        JtfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfDiaChiActionPerformed(evt);
            }
        });

        JlbTenThongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JlbTenThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbTenThongTin.setText("THÔNG TIN NHÂN VIÊN");
        JlbTenThongTin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JlbNgaySinh.setText("Ngày sinh");

        JlbGioiTinh.setText("Giới tính");

        JcbGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JcbGioiTinh.setForeground(new java.awt.Color(255, 0, 0));
        JcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        JcbGioiTinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbGioiTinhItemStateChanged(evt);
            }
        });
        JcbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbGioiTinhActionPerformed(evt);
            }
        });

        JcbChucVu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JcbChucVu.setForeground(new java.awt.Color(255, 0, 0));
        JcbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chủ phần mền quản lý", "Quản trị hệ thống", "Quản Lý", "Nhân Viên" }));
        JcbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbChucVuActionPerformed(evt);
            }
        });

        JtfKinhNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfKinhNghiemActionPerformed(evt);
            }
        });

        JlbKinhNghiem.setText("Kinh nghiệm");

        JlbPhongBan.setText("Phòng ban");

        JlbSdt.setText("SĐT");

        JlbEmail.setText("Email");

        JtfSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfSdtActionPerformed(evt);
            }
        });

        JtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfEmailActionPerformed(evt);
            }
        });

        JlbLuong.setText("Lương");

        javax.swing.GroupLayout JpnThongTinLayout = new javax.swing.GroupLayout(JpnThongTin);
        JpnThongTin.setLayout(JpnThongTinLayout);
        JpnThongTinLayout.setHorizontalGroup(
            JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlbTenThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpnThongTinLayout.createSequentialGroup()
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JlbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JcbChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JpnThongTinLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JlbSdt)
                        .addGap(18, 18, 18)
                        .addComponent(JtfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(JlbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JtfTenNhanVien))
                    .addGroup(JpnThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnThongTinLayout.createSequentialGroup()
                                .addComponent(JlbKinhNghiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JtfKinhNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpnThongTinLayout.createSequentialGroup()
                                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JpnThongTinLayout.createSequentialGroup()
                                        .addComponent(JlbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JlbPhongBan)
                                        .addGap(24, 24, 24)
                                        .addComponent(JtfPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JpnThongTinLayout.createSequentialGroup()
                                        .addComponent(JlbHo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JtfHoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnThongTinLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JtfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpnThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlbNgaySinh)
                            .addComponent(JlbLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnThongTinLayout.createSequentialGroup()
                                .addComponent(JlbEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                            .addComponent(JtfDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JtfLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JtfNgaySinh))))
                .addContainerGap())
        );
        JpnThongTinLayout.setVerticalGroup(
            JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlbTenThongTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbMaNhanVien)
                    .addComponent(JtfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbTen)
                    .addComponent(JtfHoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbHo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbPhongBan)
                    .addComponent(JtfPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbGioiTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JcbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbSdt)
                    .addComponent(JlbEmail)
                    .addComponent(JtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbLuong)
                    .addComponent(JtfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbNgaySinh)
                    .addComponent(JtfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbKinhNghiem)
                    .addComponent(JtfKinhNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        JlbTieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JlbTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbTieuDe.setText("NHÂN VIÊN");
        JlbTieuDe.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout JpnTieuDeLayout = new javax.swing.GroupLayout(JpnTieuDe);
        JpnTieuDe.setLayout(JpnTieuDeLayout);
        JpnTieuDeLayout.setHorizontalGroup(
            JpnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnTieuDeLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(JlbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(JlbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
            .addComponent(JlbTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JpnTieuDeLayout.setVerticalGroup(
            JpnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JpnTieuDeLayout.createSequentialGroup()
                .addComponent(JlbTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpnTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JlbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên", "Họ", "Giới Tính", "Ngày sinh", "Chức vụ", "Lương", "Địa chỉ", "Kinh nghiệm", "Phòng ban", "SĐT", "Email"
            }
        ));
        jScrollPane1.setViewportView(Jtb);

        javax.swing.GroupLayout JpnTableLayout = new javax.swing.GroupLayout(JpnTable);
        JpnTable.setLayout(JpnTableLayout);
        JpnTableLayout.setHorizontalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnTableLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpnTableLayout.setVerticalGroup(
            JpnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        JlbTenTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JlbTenTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbTenTable.setText("BẢNG THÔNG TIN NHÂN VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JlbTenTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JpnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(JpnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(JpnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(JpnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpnTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JpnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(JlbTenTable)
                .addGap(18, 18, 18)
                .addComponent(JpnTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnXoaActionPerformed

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed
             
    }//GEN-LAST:event_BtnThemActionPerformed

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSuaActionPerformed

    private void JtfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfDiaChiActionPerformed

    private void BtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimKiemActionPerformed
      
    }//GEN-LAST:event_BtnTimKiemActionPerformed

    private void JcbGioiTinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbGioiTinhItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbGioiTinhItemStateChanged

    private void JcbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbChucVuActionPerformed

    private void JcbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbGioiTinhActionPerformed

    private void JtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfEmailActionPerformed

    private void JtfKinhNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfKinhNghiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfKinhNghiemActionPerformed

    private void JtfSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfSdtActionPerformed


   
  public static void main(String args[]) {
       
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              JFrame f =  new JFrame();
              
              f.setVisible(true);
              f.setSize(1300, 800);
               f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               NhanVienGUI fr=new NhanVienGUI();
               fr.setSize(1200, 1000);
               f.add(fr);
               
               
            }
        });
    }
  
  
  
 
/*public void listSP() // Chép ArrayList lên table
    {
        if(nvBUS.getList()== null)nvBUS.listNV();
        ArrayList<NhanVienDTO> nv = nvBUS.getList();
        model.setRowCount(0);
        outModel(model,nv);
}

         try{
       
                        //Lấy dữ liệu từ TextField
                        String maNV = JtfMaNhanVien.getText();
                        String tenNV = JtfTenNhanVien.getText();                
                        String chucVu =JtfChucVu.getText();
                        String gioiTinh =JtfGioiTinh.getText();
                        String diaChi = JtfDiaChi.getText();
                        String email = JtfEmail.getText();
                        int namSinh = Integer.parseInt(JtfNamSinh.getText());
                        int mucLuong = Integer.parseInt(JtfMucLuong.getText());
                        int sdt = Integer.parseInt(JtfSoDienThoai.getText());

                        if(nvBUS.check(maNV))
                        {
                            JOptionPane.showMessageDialog(null, "Mã nhân viên đă tồn tại !!!");
                            return;
                        }
                        //Upload nhân viên lên DAO và BUS
                        NhanVienDTO nv = new NhanVienDTO(maNV, tenNV, chucVu, gioiTinh, diaChi,  email, namSinh,  mucLuong, sdt);
                        nvBUS.Them(nv);
                        outModel(model, nvBUS.getList());// Load lại table

                     
                            
                        //cleanView();
                         }catch(NumberFormatException ex){
                            JOptionPane.showMessageDialog(null,"Loi");
                        }
                    */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCapNhat;
    private javax.swing.JButton BtnNhapExcel;
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnTimKiem;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JButton BtnXuatExcel;
    private javax.swing.JComboBox<String> JcbChucVu;
    private javax.swing.JComboBox<String> JcbGioiTinh;
    private javax.swing.JLabel JlbChucVu;
    private javax.swing.JLabel JlbDiaChi;
    private javax.swing.JLabel JlbEmail;
    private javax.swing.JLabel JlbGioiTinh;
    private javax.swing.JLabel JlbHo;
    private javax.swing.JLabel JlbKinhNghiem;
    private javax.swing.JLabel JlbLuong;
    private javax.swing.JLabel JlbMaNhanVien;
    private javax.swing.JLabel JlbNgaySinh;
    private javax.swing.JLabel JlbPhongBan;
    private javax.swing.JLabel JlbSdt;
    private javax.swing.JLabel JlbTB;
    private javax.swing.JLabel JlbTen;
    private javax.swing.JLabel JlbTenChucNang;
    private javax.swing.JLabel JlbTenTable;
    private javax.swing.JLabel JlbTenThongTin;
    private javax.swing.JLabel JlbThongBao;
    private javax.swing.JLabel JlbTieuDe;
    private javax.swing.JPanel JpnChucNang;
    private javax.swing.JPanel JpnTable;
    private javax.swing.JPanel JpnThongTin;
    private javax.swing.JPanel JpnTieuDe;
    private javax.swing.JTable Jtb;
    private javax.swing.JTextField JtfDiaChi;
    private javax.swing.JTextField JtfEmail;
    private javax.swing.JTextField JtfHoNhanVien;
    private javax.swing.JTextField JtfKinhNghiem;
    private javax.swing.JTextField JtfLuong;
    private javax.swing.JTextField JtfMaNhanVien;
    private javax.swing.JTextField JtfNgaySinh;
    private javax.swing.JTextField JtfPhongBan;
    private javax.swing.JTextField JtfSdt;
    private javax.swing.JTextField JtfTenNhanVien;
    private javax.swing.JTextField JtfTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getBackground(Color MAGENTA) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}